trigger:
- master
- develop

jobs:
  - job: UnitTest
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    - task: FlutterTest@0
      inputs:
        projectDirectory: $(projectDirectory)


