// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH4xOX8uOVhH0VbVm0-nxz2ASBDsPnGhM',
    appId: '1:518652232663:web:db6fc50b2ba964efa00192',
    messagingSenderId: '518652232663',
    projectId: 'flutter-pos-936d6',
    authDomain: 'flutter-pos-936d6.firebaseapp.com',
    databaseURL: 'https://flutter-pos-936d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-pos-936d6.appspot.com',
    measurementId: 'G-VFC4K8FLNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVxLox1RPPcj836Tak4Thi8g1sKWpFH4',
    appId: '1:518652232663:android:0e07e304a6f7a15fa00192',
    messagingSenderId: '518652232663',
    projectId: 'flutter-pos-936d6',
    databaseURL: 'https://flutter-pos-936d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-pos-936d6.appspot.com',
  );
}
