name: Flutter
on: [push]
jobs:
  test:
    name: Test ${{ matrix.channel }}:${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        version: ["", "1.22.x", "1.2.1"]
        channel: [stable, beta]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - run: dart --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
  master:
    name: "Test Flutter master channel: on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@master
        with:
          channel: master
      - run: flutter --version
      - run: dart --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
